### ISSUE TITLE
Support for merging from multiple files on load

### ISSUE THREAD

**Issue by lrolsen1** [welbornprod/easysettings#12]
In order to simplify variable replacement in CI builds .NET allows you to specify multiple settings file when loading. The files will then be loaded and merged in order. If a variable is in multiple files the last value loaded will win. It looks something like this. 

               config.AddJsonFile("appsettings.json", optional: false)
                        .AddJsonFile("ci-appsettings.json", optional: true)

During CI build the build pipeline will then simply create a ci-appsettings.json file. 

This can also be used to seamlessly load secrets

               config.AddJsonFile("appsettings.json", optional: false) // The variables that are not secret. So they can be added to git
                        .AddJsonFile("../localsecrets.json", optional: true) // Secrets for use locally. Stored outside the git repos folder
                        .AddJsonFile("ci-appsettings.json", optional: true) // The CI variables. Typically a mix of secrets and non-secrets

In an organization with multiple git repos and where the same secrets are used in multiple applications they can then standardize on the basic variable names and then use the same localsecrets.json across multiple projects when working locally.

c:\code
  - localsecrets.json
  - app1
    - appsettings.json  
  - app2
    - appsettings.json  

Is this kind of chaining and merging possible with easysettings?

**Comment by cjwelborn** [comment]
I think it's a great idea. Anything is possible with enough code, because all EasySettings instances are just `dict`s that can be merged. I've been away from my projects for a while, but I will definitely look into this. Also, I accept any pull requests that don't break backwards compatibility. I'll see what I can do this week. Thank you for the report.

**Comment by lrolsen1** [comment]
Awesome!. I am still pretty new in Python (coming from C#) so I am not sure you would want a pull request from me at this point :)

**Comment by cjwelborn** [comment]
I forgot to mention that the `easysettings.load_settings()` function (preferred method of loading a config file, along with `load_json_settings()` and friends) accepts a `list` of filepaths, and it will load the first available file. As for merging multiple files, that will require a little work, and I will see what I can do when I have time.
