### ISSUE TITLE
I prefer to use the other *Settings classes in the easysettings package.

### ISSUE THREAD

**Issue by ghuname** [welbornprod/easysettings#5]
Hi,

can you please explain what you wanted to say with sentence: "I prefer to use the other *Settings classes in the easysettings package."

Regards.

**Comment by cjwelborn** [comment]
There is a JSONSettings class that basically allows you to easily load/save your settings as JSON. Calling `load_json_settings` works on the first run (empty or default settings object), and then you call `save()` before the program exits if you want to save any changes. There is also `TOMLSettings` and `YAMLSettings` that work the same way, but I don't use those as much either.

`EASYSettings` has a bunch of features that try to do the "right thing", and guess what the user meant. The others don't have all of that. Just `load` (or `load_<language>_settings`) and `save`. It's up to you to make sure your values are serializable in the format (JSON, YAML, TOML), but that's probably better. Less surprises. Try the [load_json_settings]( https://github.com/welbornprod/easysettings/blob/f98b91672a14b96773c39d9b27e69ecddbde3e14/easysettings/json_settings.py#L24). It's easy to use.

**Comment by ghuname** [comment]
Hi,

I have created an example:

```
from easysettings import EasySettings
import datetime as dt

settings_file = r'C:\Users\zoran\PycharmProjects\Test\myconfigfile.json'

settings = EasySettings(settings_file)

date = dt.datetime.now().date()
dtime = dt.datetime.now()

print(date, dtime)

settings.set('date', date)
settings.set('dtime', dtime)

settings.save()
```

Sometime it works, but sometimes I get:

```
C:\Users\user\Miniconda3\python.exe C:/Users/user/PycharmProjects/Test/easy_settings_test.py
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\lib\site-packages\easysettings\easy_settings.py", line 665, in save
    fwrite.write(skey + '=' + sval + '\n')
2019-12-23 2019-12-23 19:08:17.036639
  File "C:\Users\user\Miniconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x8f' in position 99: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/Test/easy_settings_test.py", line 16, in <module>
    settings.save()
  File "C:\Users\user\Miniconda3\lib\site-packages\easysettings\easy_settings.py", line 672, in save
    raise esSaveError(ex)
easysettings.easy_settings.esSaveError: 'charmap' codec can't encode character '\x8f' in position 99: character maps to <undefined>

Process finished with exit code 1
```

Regards.

**Comment by cjwelborn** [comment]
I'm sure it's because `pickle` is producing a weird string for certain dates that doesn't mix well with utf-8 encoded files. I'll see what I can do to help that and get back to you. I hadn't tested with dates or datetimes, but it looks like pickle can handle them so I just need to help it along.

On another note, the file extension for your config file should be `.conf`, or maybe `.es` because the format for that file is basically EasySettings' custom format. `.json` is reserved for JSON files, which you are not using right now. It won't help with your current problem though. I'll get back to you on that.

**Comment by cjwelborn** [comment]
I added basic `date`/`datetime` support. If you need the dates in any other format, you will need to serialize them *before* setting them in `EasySettings` (as in: `settings.set('now', mydate.strftime('%H-%M-%D'))`).

**Comment by ghuname** [comment]
This is very nice improvement. 
This is what I got in my config file:
```
date=2019-12-26T00:00:00Z
dtime=2019-12-26T17:42:19Z
```
I am not complaining, but is there an option to change date/dtime format?
For example, for date to be with no time part, and for datetime to be like '2019-12-26 17:42:19'.

**Comment by cjwelborn** [comment]
You can, since you know the setting will be a date, just convert it to a string yourself and then save it. When you load the setting, convert it back into a date (`mydatetime.strftime()` and `datetime.strfpime()`, with whatever format string you want).
