### ISSUE TITLE
Support multiple configuration files

### ISSUE THREAD

**Issue by ziima** [welbornprod/easysettings#7]
It would be really handy, if the high level functions support multiple configuration files. First file found would be used as configuration. This would allow passing a lists with common locations such as `['./foo.config', '~/.foo.config', '/etc/foo.config']`.

**Comment by cjwelborn** [comment]
Yeh, I like that. Should be an easy feature to implement.

**Comment by cjwelborn** [comment]
This is in `3.3.3`. Thank you.
